name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: MLX Whisper GUI ${{ github.ref }}
        body: |
          ## Features
          - Advanced progress tracking with ETA estimation
          - MLX Whisper large-v3 for highest accuracy
          - Batch processing support
          - Auto-save transcripts
          - Single instance application
          
          ## Installation
          1. Download `MLXWhisperGUI.dmg` 
          2. Double-click to mount
          3. Drag app to Applications folder
          
          ## Requirements
          - Apple Silicon Mac (M1/M2/M3/M4)
          - macOS 12.0+ (Monterey or later)
          
          See README.md for detailed information.
        draft: false
        prerelease: false